package com.kpit.pojo;

// Generated Dec 22, 2016 5:10:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeptName generated by hbm2java
 */
@Entity
@Table(name = "dept_name", catalog = "student_info")
public class DeptName implements java.io.Serializable {

	private Integer deptId;
	private String deptName;
	private Set<MasterStudent> masterStudents = new HashSet<MasterStudent>(0);
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public DeptName() {
	}

	public DeptName(String deptName) {
		this.deptName = deptName;
	}

	public DeptName(String deptName, Integer deptId_1, String deptName_1, Set<MasterStudent> masterStudents,
			Set<Staff> staffs) {
		this.deptName = deptName;
		this.masterStudents = masterStudents;
		this.staffs = staffs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Dept_Id", unique = true, nullable = false)
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Column(name = "Dept_Name", nullable = false)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deptName")
	public Set<MasterStudent> getMasterStudents() {
		return this.masterStudents;
	}

	public void setMasterStudents(Set<MasterStudent> masterStudents) {
		this.masterStudents = masterStudents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deptName")
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

	@Override
	public String toString() {
		return "DeptName [deptId=" + deptId + ", deptName=" + deptName + "]";
	}
}
