package com.kpit.pojo;

// Generated Dec 22, 2016 5:10:09 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExamResult generated by hbm2java
 */
@Entity
@Table(name = "exam_result", catalog = "student_info")
public class ExamResult implements java.io.Serializable {

	private Integer resultId;
	private MasterStudent masterStudent;
	private double sub1;
	private double sub2;
	private double sub3;
	private double result;
	private String resultStatus;

	public ExamResult() {
	}

	public ExamResult(MasterStudent masterStudent, double sub1, double sub2, double sub3, double result,
			String resultStatus) {
		this.masterStudent = masterStudent;
		this.sub1 = sub1;
		this.sub2 = sub2;
		this.sub3 = sub3;
		this.result = result;
		this.resultStatus = resultStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Result_Id", unique = true, nullable = false)
	public Integer getResultId() {
		return this.resultId;
	}

	public void setResultId(Integer resultId) {
		this.resultId = resultId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Stud_Id", nullable = false)
	public MasterStudent getMasterStudent() {
		return this.masterStudent;
	}

	public void setMasterStudent(MasterStudent masterStudent) {
		this.masterStudent = masterStudent;
	}

	@Column(name = "Sub1", nullable = false, precision = 22, scale = 0)
	public double getSub1() {
		return this.sub1;
	}

	public void setSub1(double sub1) {
		this.sub1 = sub1;
	}

	@Column(name = "Sub2", nullable = false, precision = 22, scale = 0)
	public double getSub2() {
		return this.sub2;
	}

	public void setSub2(double sub2) {
		this.sub2 = sub2;
	}

	@Column(name = "Sub3", nullable = false, precision = 22, scale = 0)
	public double getSub3() {
		return this.sub3;
	}

	public void setSub3(double sub3) {
		this.sub3 = sub3;
	}

	@Column(name = "Result", nullable = false, precision = 22, scale = 0)
	public double getResult() {
		return this.result;
	}

	public void setResult(double result) {
		this.result = result;
	}

	@Column(name = "Result_Status", nullable = false)
	public String getResultStatus() {
		return this.resultStatus;
	}

	public void setResultStatus(String resultStatus) {
		this.resultStatus = resultStatus;
	}

	@Override
	public String toString() {
		return "ExamResult [resultId=" + resultId + ", sub1=" + sub1 + ", sub2=" + sub2 + ", sub3=" + sub3 + ", result="
				+ result + ", resultStatus=" + resultStatus + "]";
	}

}
