package com.kpit.pojo;

// Generated Dec 22, 2016 5:10:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MasterStudent generated by hbm2java
 */
@Entity
@Table(name = "master_student", catalog = "student_info")
public class MasterStudent implements java.io.Serializable {

	private Integer studId;
	private DeptName deptName;
	private String studName;
	private String studAddress;
	private String studEmail;
	private Set<ExamResult> examResults = new HashSet<ExamResult>(0);
	private Set<Fees> feeses = new HashSet<Fees>(0);
	private Set<StudEventParticipation> studEventParticipations = new HashSet<StudEventParticipation>(0);

	public MasterStudent() {
	}

	public MasterStudent(DeptName deptName, String studName, String studAddress, String studEmail) {
		this.deptName = deptName;
		this.studName = studName;
		this.studAddress = studAddress;
		this.studEmail = studEmail;
	}

	public MasterStudent(Integer studentId, DeptName deptName, String studName, String studAddress, String studEmail) {
		this.studId = studentId;
		this.deptName = deptName;
		this.studName = studName;
		this.studAddress = studAddress;
		this.studEmail = studEmail;
	}

	public MasterStudent(DeptName deptName, String studName, String studAddress, String studEmail,
			Set<ExamResult> examResults, Set<Fees> feeses, Set<StudEventParticipation> studEventParticipations) {
		this.deptName = deptName;
		this.studName = studName;
		this.studAddress = studAddress;
		this.studEmail = studEmail;
		this.examResults = examResults;
		this.feeses = feeses;
		this.studEventParticipations = studEventParticipations;
	}

	@Id

	@Column(name = "Stud_Id", unique = true, nullable = false)
	public Integer getStudId() {
		return this.studId;
	}

	public void setStudId(Integer studId) {
		this.studId = studId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dept_Id", nullable = false)
	public DeptName getDeptName() {
		return this.deptName;
	}

	public void setDeptName(DeptName deptName) {
		this.deptName = deptName;
	}

	@Column(name = "Stud_Name", nullable = false)
	public String getStudName() {
		return this.studName;
	}

	public void setStudName(String studName) {
		this.studName = studName;
	}

	@Column(name = "Stud_Address", nullable = false)
	public String getStudAddress() {
		return this.studAddress;
	}

	public void setStudAddress(String studAddress) {
		this.studAddress = studAddress;
	}

	@Column(name = "Stud_Email", nullable = false)
	public String getStudEmail() {
		return this.studEmail;
	}

	public void setStudEmail(String studEmail) {
		this.studEmail = studEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterStudent")
	public Set<ExamResult> getExamResults() {
		return this.examResults;
	}

	public void setExamResults(Set<ExamResult> examResults) {
		this.examResults = examResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterStudent")
	public Set<Fees> getFeeses() {
		return this.feeses;
	}

	public void setFeeses(Set<Fees> feeses) {
		this.feeses = feeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "masterStudent")
	public Set<StudEventParticipation> getStudEventParticipations() {
		return this.studEventParticipations;
	}

	public void setStudEventParticipations(Set<StudEventParticipation> studEventParticipations) {
		this.studEventParticipations = studEventParticipations;
	}

	@Override
	public String toString() {
		return "MasterStudent [studId=" + studId + ", studName=" + studName + ", studAddress=" + studAddress
				+ ", studEmail=" + studEmail + "]";
	}

}
