package com.kpit.pojo;

// Generated Dec 22, 2016 5:10:09 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudEventParticipation generated by hbm2java
 */
@Entity
@Table(name = "stud_event_participation", catalog = "student_info")
public class StudEventParticipation implements java.io.Serializable {

	private Integer studEventId;
	private MasterStudent masterStudent;
	private String eventParticipation;

	public StudEventParticipation() {
	}

	public StudEventParticipation(MasterStudent masterStudent, String eventParticipation) {
		this.masterStudent = masterStudent;
		this.eventParticipation = eventParticipation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Stud_Event_Id", unique = true, nullable = false)
	public Integer getStudEventId() {
		return this.studEventId;
	}

	public void setStudEventId(Integer studEventId) {
		this.studEventId = studEventId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Stud_Id", nullable = false)
	public MasterStudent getMasterStudent() {
		return this.masterStudent;
	}

	public void setMasterStudent(MasterStudent masterStudent) {
		this.masterStudent = masterStudent;
	}

	@Column(name = "Event_Participation", nullable = false)
	public String getEventParticipation() {
		return this.eventParticipation;
	}

	public void setEventParticipation(String eventParticipation) {
		this.eventParticipation = eventParticipation;
	}

	@Override
	public String toString() {
		return "StudEventParticipation [studEventId=" + studEventId + ", eventParticipation=" + eventParticipation
				+ "]";
	}

}
